In [1]:
import pandas as pd
data = pd.read_csv('../data/preprocess_train.csv')

In [16]:
data

,sample_id,feature0,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,...,feature98,feature99,feature100,feature101,feature102,feature103,feature104,feature105,feature106,label
0,0,51.567250,288358.400000,NaN,1.855900,201.460169,6.582261,-0.516321,5.636771e+11,2.222212e+05,...,3.145963e+04,254.582034,0.0,-2.014506e+08,159.299350,0.603211,NaN,-5.256075,180.977310,4
1,1,63.804874,288358.400000,1.106802,1.050387,391.605375,13.323439,4.662871,NaN,-1.442474e+05,...,4.283053e+04,270.580779,0.0,-1.534970e+09,NaN,0.506220,0.552654,16.505952,314.783263,5
2,2,49.138527,288358.400000,1.111649,0.767127,130.708067,6.485547,5.696815,5.474603e+11,-4.288403e+05,...,2.499632e+05,160.207067,0.0,7.998345e+08,112.632639,0.080100,0.235920,64.707581,183.304610,2
3,3,NaN,288358.400000,1.109169,NaN,258.521076,0.716737,23.238461,-3.539891e+11,NaN,...,1.254783e+05,196.223295,0.0,-9.246920e+07,138.431470,2.548783,1.414810,-9.662399,212.302670,2
4,4,76.520831,288358.400000,1.113410,5.795408,256.038997,-1.803483,14.040495,-1.071014e+11,6.499723e+05,...,1.862664e+05,179.083883,0.0,-6.796351e+08,259.858740,0.337643,0.228832,59.733069,135.541233,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6291,6291,70.406112,288358.400000,1.098904,0.134016,222.782078,8.751254,21.783621,-9.018455e+11,-4.047841e+05,...,5.235188e+04,217.577771,0.0,-9.042319e+06,203.750885,0.102876,2.385235,-3.557545,154.955008,0
6292,6292,72.795989,288358.400000,NaN,0.503558,408.101229,22.436609,5.631515,-2.376201e+11,-4.051203e+05,...,NaN,178.635641,0.0,3.529909e+08,162.268924,0.824727,1.279274,-8.085779,231.487352,0
6293,6293,71.210154,515352.218703,2.101946,13.816881,-78.826173,111.744022,50.800576,5.065975e+12,4.996345e+06,...,1.662894e+06,-76.537164,0.0,-7.378573e+08,137.228629,12.985847,0.143317,139.819816,-103.883245,0
6294,6294,NaN,288358.400000,1.106200,1.001885,218.883538,9.064199,9.285105,-2.020482e+10,-1.285311e+04,...,7.515669e+04,NaN,0.0,3.383887e+08,199.620984,0.476171,NaN,-30.718727,183.050026,0
6295,6295,37.408452,288358.400000,1.101254,NaN,99.875245,9.159279,-1.218270,-4.647698e+11,6.104908e+04,...,3.812138e+04,291.144747,0.0,5.365031e+08,255.460715,0.513641,2.563858,-13.845655,284.550988,0

In [17]:
data.iloc[:, 0]

0          0
1          1
2          2
3          3
4          4
        ...
6291    6291
6292    6292
6293    6293
6294    6294
6295    6295
Name: sample_id, Length: 6296, dtype: int64

In [18]:
import numpy as np

In [19]:
arr = np.asarray(data.iloc[:, 0])

In [20]:
arr

array([   0,    1,    2, ..., 6293, 6294, 6295], dtype=int64)

In [21]:
data = pd.read_csv('../data/preprocess_train.csv')

In [23]:
data1000 = data.sample(n=1000, replace=False)

In [24]:
data1000

,sample_id,feature0,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,...,feature98,feature99,feature100,feature101,feature102,feature103,feature104,feature105,feature106,label
2847,2847,64.685536,288358.4,1.107554,0.577510,122.943731,3.049828,5.948751,1.753313e+11,NaN,...,NaN,123.819575,0.0,-2.872923e+08,165.196768,2.485842,2.805659,1.716125,193.212845,0
606,606,29.431306,288358.4,2.107559,0.116808,217.697674,4.822540,-1.775048,NaN,-414283.762511,...,78366.761380,230.830967,0.0,1.314711e+09,254.542752,0.934304,1.776437,33.044870,286.438301,1
5754,5754,NaN,288358.4,NaN,0.426567,291.900308,2.608100,-4.865133,3.595630e+11,287730.079144,...,217573.795332,243.081412,0.0,4.649387e+06,224.782925,0.530485,1.231444,-18.236418,291.868078,2
1116,1116,51.134391,288358.4,NaN,NaN,275.144721,20.722953,3.790292,-1.967326e+10,-585869.106558,...,184677.407393,323.163819,0.0,3.025648e+08,208.916080,0.685874,1.665851,-3.129446,164.685378,0
1044,1044,75.716630,288358.4,1.098828,1.567705,193.637512,16.073960,11.499766,-9.609266e+09,518169.692897,...,78098.810391,252.060738,0.0,-3.039246e+08,143.827151,0.373955,1.347128,-5.578469,226.064940,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1678,1678,81.822785,288358.4,1.101071,1.222203,NaN,6.663814,8.708339,3.170381e+11,-308669.085854,...,74585.621112,287.844105,0.0,3.417816e+07,214.636434,1.299213,1.349838,5.848508,190.819795,2
1500,1500,63.327254,288358.4,1.104370,0.331997,276.370489,14.133216,-13.383635,NaN,-383192.748546,...,46694.952604,263.946837,0.0,-3.528531e+08,144.137371,0.253859,0.935849,2.455991,338.221341,5
4003,4003,85.966590,288358.4,1.105322,0.668572,318.041954,7.395121,-0.161341,3.716003e+11,-234239.209810,...,750.379879,217.178862,0.0,-3.496507e+08,170.232664,0.100463,2.816584,0.458072,97.349704,0
1603,1603,21.780707,288358.4,1.104396,NaN,297.044429,8.188491,11.218000,-1.830471e+08,-245645.990457,...,222513.473939,273.785636,0.0,-6.221081e+08,167.397238,0.266824,1.726871,6.490379,303.903670,1
3475,3475,81.518365,288358.4,1.098201,0.268730,194.189715,5.106302,-11.007320,-3.973812e+11,550281.809908,...,204730.450093,173.098491,0.0,-8.855268e+07,139.596423,0.457515,2.676866,17.715114,280.762831,0

In [25]:
data1000.to_csv('train_data_1000.csv', index=False)

In [27]:
data500 = data.sample(n=500, replace=False)
data500.to_csv('train_data_500.csv', index=False)

In [28]:
data200 = data.sample(n=200, replace=False)
data200.to_csv('train_data_200.csv', index=False)

In [29]:
data100 = data.sample(n=100, replace=False)
data100.to_csv('train_data_100.csv', index=False)

In [34]:
data1000 = data.sample(n=1000, replace=False)
data1000.to_csv('train_data_1000.csv', index=False)

In [35]:
data2000 = data.sample(n=2000, replace=False)
data2000.to_csv('train_data_2000.csv', index=False)

In [36]:
data5000 = data.sample(n=5000, replace=False)
data5000.to_csv('train_data_5000.csv', index=False)

In [30]:
test_data_200 = data.sample(n=200, replace=False)
test_data_200 = test_data_200.drop('label', axis=1)
test_data_200.to_csv('test_data_200.csv', index=False)

In [31]:
test_data_100 = data.sample(n=100, replace=False)
test_data_100 = test_data_100.drop('label', axis=1)
test_data_100.to_csv('test_data_100.csv', index=False)

In [32]:
test_data_500 = data.sample(n=500, replace=False)
test_data_500 = test_data_500.drop('label', axis=1)
test_data_500.to_csv('test_data_500.csv', index=False)

In [33]:
test_data_1000 = data.sample(n=1000, replace=False)
test_data_1000 = test_data_1000.drop('label', axis=1)
test_data_1000.to_csv('test_data_1000.csv', index=False)

In [3]:
test_data_50 = data.sample(n=50, replace=False).drop('label', axis=1)
test_data_50.to_csv('test_data_50.csv', index=False)

In [4]:
test_data_20 = data.sample(n=20, replace=False).drop('label', axis=1)
test_data_20.to_csv('test_data_20.csv', index=False)

In [5]:
test_data_10 = data.sample(n=10, replace=False).drop('label', axis=1)
test_data_10.to_csv('test_data_10.csv', index=False)

In [7]:
test_data_1 = data.sample(n=1, replace=False).drop('label', axis=1)
test_data_1.to_csv('test_data_1.csv', index=False)

In [8]:
test_data_5 = data.sample(n=5, replace=False).drop('label', axis=1)
test_data_5.to_csv('test_data_5.csv', index=False)

In [1]:
import pandas as pd
data = pd.read_csv('../data/preprocess_train.csv')

In [2]:
# Nan值解决
dict = {}
for column in data.columns.values:
    dict[column] = data[column].mean()
data = data.fillna(dict)

In [ ]:
# 抽100条